services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /opt/homelab/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.rule=Host(`ha.homelab.iot`)"
      - "traefik.http.routers.ha.entrypoints=web"
      - "traefik.http.routers.ha.service=ha"
      - "traefik.http.services.ha.loadbalancer.server.url=http://192.168.20.30:8123"

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    restart: always
    privileged: true
    volumes:
      - /opt/homelab/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host   # ESPHome dashboard port
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - USERNAME=${esphome-username}
      - PASSWORD=${esphome-password}
    labels:
      - "traefik.enable=true"    
      # Router
      - "traefik.http.routers.esphome.rule=Host(`esphome.homelab.iot`)"
      - "traefik.http.routers.esphome.entrypoints=web"
      - "traefik.http.routers.esphome.service=esphome"    
      # Backend
      - "traefik.http.services.esphome.loadbalancer.server.url=http://192.168.20.30:6052"

