services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /opt/homelab/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.rule=Host(`ha.homelab.iot`)"
      - "traefik.http.routers.ha.entrypoints=web"
      - "traefik.http.routers.ha.service=ha"
      #- "traefik.http.services.ha.loadbalancer.server.url=http://host.docker.internal:8123"
      - "traefik.http.services.ha.loadbalancer.server.port=8123"
      - "traefik.http.services.ha.loadbalancer.server.url=http://192.168.20.130:8123"

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:stable
    restart: always
    privileged: true
    volumes:
      - /opt/homelab/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host   # ESPHome dashboard port
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - USERNAME=${ESPHOME_USERNM}
      - PASSWORD=${ESPHOME_PASSWRD}
    labels:
      - "traefik.enable=true"    
      # Router
      - "traefik.http.routers.esphome.rule=Host(`esphome.homelab.iot`)"
      - "traefik.http.routers.esphome.entrypoints=web"
      - "traefik.http.routers.esphome.service=esphome"    
      # Backend            
      #- "traefik.http.services.ha.loadbalancer.server.url=http://host.docker.internal:6052"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052"
      - "traefik.http.services.esphome.loadbalancer.server.url=http://192.168.20.130:6052"


  wyze-bridge:
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:latest
    restart: unless-stopped
    network_mode: host
    ports:
      - 1935:1935 # RTMP
      - 8554:8554 # RTSP
      - 8888:8888 # HLS
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5000:5000 # WEB-UI
    environment:
      # Required: Wyze Developer Portal Account Credentials and API Keys
      - WYZE_EMAIL=${WYZE_USERNM}
      - WYZE_PASSWORD=${WYZE_PASSWRD}
      - API_ID=${WYZE_API_ID}
      - API_KEY=${WYZE_API_KEY}

      # WyzeBridge web interface settings
      - WB_AUTH=False          # Turn off Authentication for now until I can figure out the RSTP stream issue with Home Assistant
      # - WB_USERNAME=${WYZE_USERNM}    #Dashboard username for accessing the Wyze Bridge web interface     
      # - WB_PASSWORD=${WYZE_PASSWRD}   #Dashboard Password for accessing the Wyze Bridge web interface
      #- NET_MODE=LAN              # Forces local connection mode to the camera
      - NET_MODE=ANY
      - WB_IP=192.168.20.130      # Sets the IP address of the host machine for local streaming
    volumes:
      - /opt/homelab/wyzebridge/config/tokens:/tokens
    labels:
      - "traefik.enable=true"    
      # Router
      - "traefik.http.routers.wyzebridge.rule=Host(`wyzebridge.homelab.iot`)"
      - "traefik.http.routers.wyzebridge.entrypoints=web"
      - "traefik.http.routers.wyzebridge.service=wyzebridge" 
      - "traefik.http.services.wyzebridge.loadbalancer.server.port=8554" 
      - "traefik.http.services.wyzebridge.loadbalancer.server.url=http://192.168.20.130:8554"